# Site settings
title: Dylan's awesome blog
email: 264022152@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Every time I'm blogging, I was thinking what else I could bullshit.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Dillance
github_username:  angry-Dylan

# Build settings
markdown: kramdown
